{application,todo,
             [{applications,[kernel,stdlib,elixir,logger]},
              {description,"todo"},
              {modules,['Elixir.Todo.Cache','Elixir.Todo.Database',
                        'Elixir.Todo.DatabaseWorker','Elixir.Todo.List',
                        'Elixir.Todo.ProcessRegistry','Elixir.Todo.Server',
                        'Elixir.Todo.System']},
              {registered,[]},
              {vsn,"0.1.0"}]}.
